////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// GMCTWaveformAnalysis                                                       //
//                                                                            //
// Begin_Html <!--
/*-->

<!--*/
// --> End_Html
//                                                                            //
//                                                                            //
// Please note: The following information is only correct after executing     //
// the ROMEBuilder.                                                           //
//                                                                            //
// This task accesses the following folders :                                 //
//     Hit                                                                    //
//                                                                            //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                        */
#include "generated/GMCTWaveformAnalysisGeneratedIncludes.h"

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/GMCAnalyzer.h"
#include "tasks/GMCTWaveformAnalysis.h"
#include "ROMEiostream.h"

// uncomment if you want to include headers of all folders
//#include "GMCAllFolders.h"


ClassImp(GMCTWaveformAnalysis)

//______________________________________________________________________________
void GMCTWaveformAnalysis::Init()
{
}

//______________________________________________________________________________
void GMCTWaveformAnalysis::BeginOfRun()
{
}

//______________________________________________________________________________
void GMCTWaveformAnalysis::Event()
{

  Int_t nHit = gAnalyzer->GetHitSize();
  ////FAKE HIT FOR DEBUGGING PURPOSES
  gAnalyzer->SetHitSize(nHit+1);//set hit size
  Double_t random_fake=0.;
  gAnalyzer->GetHitAt(nHit)->Sett_meas(random_fake);//central tube 
  gAnalyzer->GetHitAt(nHit)->Settube_nr(gAnalyzer->GetGSP()->Getcentral_tube());
  //////

}

//______________________________________________________________________________
void GMCTWaveformAnalysis::EndOfRun()
{
}

//______________________________________________________________________________
void GMCTWaveformAnalysis::Terminate()
{
}

